# Generated by Django 3.0.4 on 2020-04-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'commodity_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'district_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'state_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(default=None, max_length=30)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.Commodity')),
            ],
            options={
                'db_table': 'variety_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(default=None, max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.District')),
            ],
            options={
                'db_table': 'market_info',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.State'),
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('modal_price', models.FloatField(blank=True, max_length=50, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.Commodity')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.District')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.Market')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.State')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.Variety')),
            ],
            options={
                'db_table': 'commodity_price_info',
                'ordering': ['arrival_date'],
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmapp.Market'),
        ),
    ]
